Otchet1
nvs174/POIP pull request #1
Opened 2023-09-22 12:46 UTC by nvs174

Работа выполнена

2023-09-23 07:53 UTC, lamer0k commented on test.adoc
> +=  Принцип запуска программного обеспечения на микроконтроллере
Зачем репозиторий назвал Work_1? На каждый отчет будешь новый репозиторий делать? Назови его просто POIP.

2023-09-23 07:53 UTC, lamer0k commented on test.adoc
> +
Надо шапку, оглавление

2023-09-23 07:54 UTC, lamer0k commented on test.adoc
> +
Нет ответов на вопросы....

2023-09-23 07:55 UTC, lamer0k commented on test.adoc
> +.. Выполнение перехода на нулевой адрес, по этому адресу лежит таблица векторов прерывания;
в нашем случае не на нулевой а на 0x800000 - там действительно лежит таблица векторов прерывания и первым делом происходит инциализация указателя стека на адрес стека.

2023-09-23 07:56 UTC, lamer0k commented on test.adoc
> +... Вектор прерываний Start - инициализирует глобальные переменные значения, которым присвоено нулевое "0" значение  и переменные, которым не присвоены никакие значение.
Вектор это просто адрес, а вот фкнкция, которая лежит по этому адресу - вот она инциализирует глобальные переменные....

2023-09-23 07:56 UTC, lamer0k commented on test.adoc
> +... Затем следует инициализация остальных переменных, которым присвоены какие-либо значения.
Как это делается? где лежат эти значения?

2023-09-23 07:58 UTC, lamer0k commented on test.adoc
> +.. После выполнения кода программы, с помощью счетчика, повышается адрес на единицу и контроллер переходит на выполнение следующей команды, прописанной в этом адресе.
Это не после выполнения программы, это вообще так работает микроконтрллер, с каждым тактом у него счечик программы увеличивается на 1 и он переходит на следующий адрес, где лежит команда, он её выполняет и переходит на след удрес.

2023-09-23 07:58 UTC, lamer0k requested changes
Пару вопросов.

2023-10-09 16:34 UTC, nvs174 commented on test.adoc
> +.. После выполнения кода программы, с помощью счетчика, повышается адрес на единицу и контроллер переходит на выполнение следующей команды, прописанной в этом адресе.
Поправил

2023-10-09 16:34 UTC, nvs174 commented on test.adoc
> +... Затем следует инициализация остальных переменных, которым присвоены какие-либо значения.
Дописал

2023-10-09 16:34 UTC, nvs174 commented on test.adoc
> +.. Выполнение перехода на нулевой адрес, по этому адресу лежит таблица векторов прерывания;
Исправил на адрес  0x800000

2023-10-09 16:34 UTC, nvs174 commented on test.adoc
> +
Ответы на вопросы находятся с 61 по 88 строки

2023-10-09 16:34 UTC, nvs174 commented on test.adoc
> +
Исправил

2023-10-09 16:34 UTC, nvs174 commented on test.adoc
> +=  Принцип запуска программного обеспечения на микроконтроллере
Изменил название на: POIP

2023-10-28 06:56 UTC, lamer0k approved these changes

2023-11-18 11:39 UTC, merged